# Reference: https://build-cpp.github.io/cmkr/cmake-toml
[project]
name = "vmdevirt-vtil"
cmake-before = """
set(ASMJIT_STATIC true)
"""

[subdir.deps]

# TODO: define a target for each of your executables/libraries like this:
#[target.myexecutable]
#type = "executable" # static, shared
#sources = ["src/vmdevirt-vtil/*.cpp", "include/vmdevirt-vtil/*.hpp"]
#include-directories = ["include"]
#compile-features = ["cxx_std_11"]
#link-libraries = ["target-or-library"]

[target.vmdevirt-vtil]
type = "executable"
sources = ["src/**.cpp", "include/**.hpp"]
include-directories = ["include", "includes", "deps/VTIL-Core/VTIL/includes"]
compile-features = ["cxx_std_20"]
link-libraries = [
    "vmemu",
    "VTIL",
    "asmjit::asmjit"
]